IDLE = "IDLE"

WAITING_VIDEO = "WAITING_VIDEO"

WAITING_TITLE = "WAITING_TITLE"

WAITING_DESCRIPTION = "WAITING_DESCRIPTION"

WAITING_THUMBNAIL = "WAITING_THUMBNAIL"

WAITING_VISIBILITY = "WAITING_VISIBILITY"

UPLOADING = "UPLOADING"

WAITING_YOUTUBE_AUTH = "WAITING_YOUTUBE_AUTH"

WAITING_DRIVE_FOLDER = "WAITING_DRIVE_FOLDER"

WAITING_DRIVE_CUSTOM_TITLE = "WAITING_DRIVE_CUSTOM_TITLE"
